# -*- coding: utf-8 -*-
"""gossip_protocol.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feafi4aiO1EfaYUcqe2Kdc_A1BSad9J1
"""

"""
MeshWeaver - Module 6
Gossip Protocol

Purpose:
    Periodically share CPU and RAM utilisation with neighbouring
    MeshWeaver nodes.

Designed for:
    - Google Colab
    - asyncio
    - later integration with Kademlia
    - later integration with MeshWeaver task routing

No external project files are required to RUN this module's
local demonstration.

No asyncio.run() is used, because Google Colab already has
an active asyncio event loop.
"""

import asyncio
import random
import time
import uuid
import os


# ============================================================
# CONFIGURATION
# ============================================================

GOSSIP_INTERVAL = 5.0

DEFAULT_FANOUT = 3

MESSAGE_TYPE = "GOSSIP_LOAD"

STALE_AFTER = 20.0


# ============================================================
# RESOURCE MONITOR
# ============================================================

def get_cpu_ram():

    # --------------------------------------------------------
    # Try psutil if already available.
    # --------------------------------------------------------

    try:

        import psutil

        cpu = float(
            psutil.cpu_percent(
                interval=None
            )
        )

        ram = float(
            psutil.virtual_memory().percent
        )

        return {
            "cpu_percent": round(
                cpu,
                2
            ),

            "ram_percent": round(
                ram,
                2
            )
        }

    except Exception:

        # ----------------------------------------------------
        # Safe fallback.
        # ----------------------------------------------------

        try:

            load = os.getloadavg()[0]

            cpu_count = (
                os.cpu_count()
                or 1
            )

            cpu = (
                load
                / cpu_count
                * 100
            )

            cpu = max(
                0.0,
                min(100.0, cpu)
            )

        except Exception:

            cpu = 0.0

        return {
            "cpu_percent": round(
                cpu,
                2
            ),

            "ram_percent": 0.0
        }


# ============================================================
# GOSSIP MESSAGE
# ============================================================

class GossipMessage:

    def __init__(
        self,
        sender_id,
        cpu_percent,
        ram_percent
    ):

        self.message_id = str(
            uuid.uuid4()
        )

        self.sender_id = str(
            sender_id
        )

        self.message_type = (
            MESSAGE_TYPE
        )

        self.cpu_percent = float(
            cpu_percent
        )

        self.ram_percent = float(
            ram_percent
        )

        self.timestamp = time.time()

    # --------------------------------------------------------
    # SERIALIZE
    # --------------------------------------------------------

    def to_dict(self):

        return {
            "message_id":
                self.message_id,

            "sender_id":
                self.sender_id,

            "message_type":
                self.message_type,

            "cpu_percent":
                self.cpu_percent,

            "ram_percent":
                self.ram_percent,

            "timestamp":
                self.timestamp
        }

    # --------------------------------------------------------
    # DESERIALIZE
    # --------------------------------------------------------

    @classmethod
    def from_dict(
        cls,
        data
    ):

        message = cls(
            sender_id=data[
                "sender_id"
            ],

            cpu_percent=data[
                "cpu_percent"
            ],

            ram_percent=data[
                "ram_percent"
            ]
        )

        message.message_id = data.get(
            "message_id",
            str(uuid.uuid4())
        )

        message.timestamp = float(
            data.get(
                "timestamp",
                time.time()
            )
        )

        return message


# ============================================================
# GOSSIP PROTOCOL
# ============================================================

class GossipProtocol:

    def __init__(
        self,
        node_id,
        fanout=DEFAULT_FANOUT,
        interval=GOSSIP_INTERVAL
    ):

        self.node_id = str(
            node_id
        )

        self.fanout = max(
            1,
            int(fanout)
        )

        self.interval = max(
            0.1,
            float(interval)
        )

        # ----------------------------------------------------
        # Known neighbours
        #
        # node_id -> peer object / address
        # ----------------------------------------------------

        self.neighbours = {}

        # ----------------------------------------------------
        # Latest resource information
        #
        # node_id -> information
        # ----------------------------------------------------

        self.peer_loads = {}

        # ----------------------------------------------------
        # Duplicate protection
        # ----------------------------------------------------

        self.seen_messages = {}

        # ----------------------------------------------------
        # Background task
        # ----------------------------------------------------

        self.running = False

        self.gossip_task = None

    # ========================================================
    # ADD NEIGHBOUR
    # ========================================================

    def add_neighbour(
        self,
        node_id,
        peer=None
    ):

        node_id = str(
            node_id
        )

        if node_id == self.node_id:
            return False

        self.neighbours[
            node_id
        ] = peer

        return True

    # ========================================================
    # REMOVE NEIGHBOUR
    # ========================================================

    def remove_neighbour(
        self,
        node_id
    ):

        self.neighbours.pop(
            str(node_id),
            None
        )

    # ========================================================
    # GET NEIGHBOURS
    # ========================================================

    def get_neighbours(self):

        return list(
            self.neighbours.keys()
        )

    # ========================================================
    # CREATE MESSAGE
    # ========================================================

    def create_message(self):

        load = get_cpu_ram()

        return GossipMessage(
            sender_id=self.node_id,

            cpu_percent=load[
                "cpu_percent"
            ],

            ram_percent=load[
                "ram_percent"
            ]
        )

    # ========================================================
    # RECEIVE MESSAGE
    # ========================================================

    def receive(
        self,
        message
    ):
        """
        Process an incoming gossip message.

        Returns True when the message is accepted.
        """

        # ----------------------------------------------------
        # Convert dictionary if necessary.
        # ----------------------------------------------------

        if isinstance(
            message,
            dict
        ):

            try:

                message = (
                    GossipMessage
                    .from_dict(message)
                )

            except Exception:

                return False

        if not isinstance(
            message,
            GossipMessage
        ):

            return False

        # ----------------------------------------------------
        # Ignore ourselves.
        # ----------------------------------------------------

        if (
            message.sender_id
            == self.node_id
        ):
            return False

        # ----------------------------------------------------
        # Ignore duplicate messages.
        # ----------------------------------------------------

        if (
            message.message_id
            in self.seen_messages
        ):
            return False

        self.seen_messages[
            message.message_id
        ] = time.time()

        # ----------------------------------------------------
        # Validate CPU.
        # ----------------------------------------------------

        try:

            cpu = float(
                message.cpu_percent
            )

            ram = float(
                message.ram_percent
            )

        except (
            TypeError,
            ValueError
        ):

            return False

        # ----------------------------------------------------
        # Keep values within valid range.
        # ----------------------------------------------------

        cpu = max(
            0.0,
            min(100.0, cpu)
        )

        ram = max(
            0.0,
            min(100.0, ram)
        )

        # ----------------------------------------------------
        # Ignore stale information.
        # ----------------------------------------------------

        if (
            time.time()
            - message.timestamp
            > STALE_AFTER
        ):

            return False

        # ----------------------------------------------------
        # Store latest information.
        # ----------------------------------------------------

        old = self.peer_loads.get(
            message.sender_id
        )

        if (
            old is not None
            and message.timestamp
            <= old["timestamp"]
        ):

            return False

        self.peer_loads[
            message.sender_id
        ] = {

            "node_id":
                message.sender_id,

            "cpu_percent":
                cpu,

            "ram_percent":
                ram,

            "timestamp":
                message.timestamp
        }

        return True

    # ========================================================
    # SELECT GOSSIP NEIGHBOURS
    # ========================================================

    def select_neighbours(self):

        peers = list(
            self.neighbours.items()
        )

        random.shuffle(
            peers
        )

        return peers[
            :self.fanout
        ]

    # ========================================================
    # BUILD OUTGOING GOSSIP
    # ========================================================

    def prepare_gossip(self):

        message = self.create_message()

        return [
            (
                node_id,
                peer,
                message
            )

            for node_id, peer
            in self.select_neighbours()
        ]

    # ========================================================
    # START
    # ========================================================

    async def start(
        self,
        send_function=None
    ):
        """
        Start background gossip.

        send_function is optional.

        Later integration can provide:

            async def send_function(peer, message):
                ...

        The module itself does not assume how the common
        MeshWeaver networking layer sends messages.
        """

        if self.running:
            return

        self.running = True

        self.gossip_task = asyncio.create_task(
            self._gossip_loop(
                send_function
            )
        )

    # ========================================================
    # STOP
    # ========================================================

    async def stop(self):

        self.running = False

        if self.gossip_task:

            self.gossip_task.cancel()

            try:

                await self.gossip_task

            except asyncio.CancelledError:
                pass

            self.gossip_task = None

    # ========================================================
    # GOSSIP LOOP
    # ========================================================

    async def _gossip_loop(
        self,
        send_function
    ):

        while self.running:

            try:

                await asyncio.sleep(
                    self.interval
                )

                if not self.running:
                    break

                await self.broadcast(
                    send_function
                )

                self.cleanup()

            except asyncio.CancelledError:

                break

            except Exception:

                # Never terminate the background gossip
                # task because of one bad peer/message.
                continue

    # ========================================================
    # BROADCAST
    # ========================================================

    async def broadcast(
        self,
        send_function=None
    ):

        outgoing = (
            self.prepare_gossip()
        )

        if send_function is None:

            # ------------------------------------------------
            # No networking layer connected yet.
            #
            # The message is still generated correctly.
            # ------------------------------------------------

            return [
                message.to_dict()
                for (
                    node_id,
                    peer,
                    message
                ) in outgoing
            ]

        sent = 0

        for (
            node_id,
            peer,
            message
        ) in outgoing:

            try:

                result = send_function(
                    peer,
                    message
                )

                if asyncio.iscoroutine(
                    result
                ):

                    await result

                sent += 1

            except Exception:

                continue

        return sent

    # ========================================================
    # CLEANUP
    # ========================================================

    def cleanup(self):

        now = time.time()

        # ----------------------------------------------------
        # Remove stale resource data.
        # ----------------------------------------------------

        for node_id, data in list(
            self.peer_loads.items()
        ):

            if (
                now - data["timestamp"]
                > STALE_AFTER
            ):

                self.peer_loads.pop(
                    node_id,
                    None
                )

        # ----------------------------------------------------
        # Remove old message IDs.
        # ----------------------------------------------------

        for message_id, timestamp in list(
            self.seen_messages.items()
        ):

            if (
                now - timestamp
                > 60
            ):

                self.seen_messages.pop(
                    message_id,
                    None
                )

    # ========================================================
    # GET PEER LOAD
    # ========================================================

    def get_peer_load(
        self,
        node_id
    ):

        data = self.peer_loads.get(
            str(node_id)
        )

        if data is None:
            return None

        if (
            time.time()
            - data["timestamp"]
            > STALE_AFTER
        ):

            return None

        return dict(data)

    # ========================================================
    # GET ALL LOADS
    # ========================================================

    def get_all_peer_loads(self):

        self.cleanup()

        return {
            node_id: dict(data)
            for node_id, data
            in self.peer_loads.items()
        }

    # ========================================================
    # LEAST LOADED NODE
    # ========================================================

    def get_least_loaded_peer(
        self,
        metric="cpu_percent"
    ):

        if metric not in (
            "cpu_percent",
            "ram_percent"
        ):

            raise ValueError(
                "metric must be cpu_percent "
                "or ram_percent"
            )

        loads = (
            self.get_all_peer_loads()
        )

        if not loads:
            return None

        return min(
            loads.values(),
            key=lambda data:
                data[metric]
        )

    # ========================================================
    # STATUS
    # ========================================================

    def status(self):

        return {

            "node_id":
                self.node_id,

            "running":
                self.running,

            "interval":
                self.interval,

            "fanout":
                self.fanout,

            "neighbours":
                len(
                    self.neighbours
                ),

            "known_peer_loads":
                len(
                    self.peer_loads
                )
        }


# ============================================================
# SIMPLE COLAB TEST
# ============================================================

async def gossip_demo():

    print(
        "======================================"
    )

    print(
        " MeshWeaver Gossip Protocol"
    )

    print(
        "======================================"
    )

    # --------------------------------------------------------
    # Create three independent Gossip nodes.
    # --------------------------------------------------------

    node_a = GossipProtocol(
        "node-A"
    )

    node_b = GossipProtocol(
        "node-B"
    )

    node_c = GossipProtocol(
        "node-C"
    )

    # --------------------------------------------------------
    # Connect neighbours.
    # --------------------------------------------------------

    node_a.add_neighbour(
        "node-B"
    )

    node_a.add_neighbour(
        "node-C"
    )

    node_b.add_neighbour(
        "node-A"
    )

    node_b.add_neighbour(
        "node-C"
    )

    node_c.add_neighbour(
        "node-A"
    )

    node_c.add_neighbour(
        "node-B"
    )

    # --------------------------------------------------------
    # Create one gossip message.
    # --------------------------------------------------------

    message = node_a.create_message()

    print(
        "\nNode-A generated:"
    )

    print(
        message.to_dict()
    )

    # --------------------------------------------------------
    # Deliver it to B and C.
    # --------------------------------------------------------

    accepted_b = node_b.receive(
        message
    )

    accepted_c = node_c.receive(
        message
    )

    print(
        "\nNode-B accepted:",
        accepted_b
    )

    print(
        "Node-C accepted:",
        accepted_c
    )

    # --------------------------------------------------------
    # Display received information.
    # --------------------------------------------------------

    print(
        "\nNode-B knows:"
    )

    print(
        node_b.get_all_peer_loads()
    )

    print(
        "\nNode-C knows:"
    )

    print(
        node_c.get_all_peer_loads()
    )

    # --------------------------------------------------------
    # Test duplicate protection.
    # --------------------------------------------------------

    duplicate = node_b.receive(
        message
    )

    print(
        "\nDuplicate accepted:",
        duplicate
    )

    print(
        "\nGossip test completed successfully."
    )


# ============================================================
# COLAB EXECUTION
# ============================================================
#
# IMPORTANT:
#
# In Google Colab run:
#
#     await gossip_demo()
#
# Do NOT use:
#
#     asyncio.run(gossip_demo())
#
# ============================================================