# -*- coding: utf-8 -*-
"""kademlia_discovery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QALDCUJC3TjXkQ4uGy27Ss_Xn5WnkQV2
"""

"""
MeshWeaver - Module 5
Kademlia Node Discovery

This module contains ONLY Kademlia discovery/routing logic.

It expects the common MeshWeaver networking layer to provide a
Node object with:

    node.node_id
    node.host
    node.port
    node.register_handler(message_type, handler)
    node.send_udp(host, port, message)

and a Message object with:

    Message(type, sender_id, payload=..., msg_id=...)

The networking layer remains separate.

Google Colab:
    Do NOT use asyncio.run() inside Colab.
    Start the integrated system with:
        await ...
"""

import asyncio
import hashlib
import logging
import random
import time
import uuid
from dataclasses import dataclass
from typing import Optional


# ============================================================
# LOGGING
# ============================================================

logger = logging.getLogger("meshweaver.kademlia")


# ============================================================
# KADEMLIA PARAMETERS
# ============================================================

ID_BITS = 160
K = 20
ALPHA = 3

RPC_TIMEOUT = 3.0
REFRESH_INTERVAL = 60.0


# ============================================================
# MESSAGE TYPES
# ============================================================

KADEMLIA_PING = "KADEMLIA_PING"
KADEMLIA_PONG = "KADEMLIA_PONG"

KADEMLIA_FIND_NODE = "KADEMLIA_FIND_NODE"
KADEMLIA_FIND_NODE_RESPONSE = "KADEMLIA_FIND_NODE_RESPONSE"


# ============================================================
# CONTACT
# ============================================================

@dataclass
class Contact:
    """
    Information required to communicate with another node.
    """

    node_id: str
    host: str
    port: int

    def to_dict(self):
        return {
            "node_id": self.node_id,
            "host": self.host,
            "port": self.port,
        }

    @classmethod
    def from_dict(cls, data):
        return cls(
            node_id=str(data["node_id"]),
            host=str(data["host"]),
            port=int(data["port"]),
        )


# ============================================================
# NODE ID
# ============================================================

def make_node_id(value=None):
    """
    Create a 160-bit Kademlia node ID.

    If value is supplied, the ID is deterministic.
    """

    if value is None:
        value = (
            str(uuid.uuid4())
            + str(time.time_ns())
            + str(random.random())
        )

    return hashlib.sha1(
        str(value).encode("utf-8")
    ).hexdigest()


# ============================================================
# XOR DISTANCE
# ============================================================

def xor_distance(node_a, node_b):
    """
    Kademlia XOR distance.
    """

    return (
        int(node_a, 16)
        ^ int(node_b, 16)
    )


# ============================================================
# BUCKET INDEX
# ============================================================

def get_bucket_index(local_id, remote_id):
    """
    Determine which Kademlia bucket contains remote_id.

    Returns None if both IDs are identical.
    """

    distance = xor_distance(
        local_id,
        remote_id
    )

    if distance == 0:
        return None

    return distance.bit_length() - 1


# ============================================================
# ROUTING TABLE
# ============================================================

class RoutingTable:

    def __init__(
        self,
        local_node_id,
        k=K
    ):

        self.local_node_id = local_node_id
        self.k = int(k)

        self.buckets = [
            []
            for _ in range(ID_BITS)
        ]

    # --------------------------------------------------------
    # ADD
    # --------------------------------------------------------

    def add(self, contact):

        if (
            not contact
            or contact.node_id
            == self.local_node_id
        ):
            return False

        try:

            index = get_bucket_index(
                self.local_node_id,
                contact.node_id
            )

        except (
            ValueError,
            TypeError
        ):

            return False

        if index is None:
            return False

        bucket = self.buckets[index]

        # Existing contact.
        for old in bucket:

            if old.node_id == contact.node_id:

                bucket.remove(old)
                bucket.append(contact)

                return True

        # Space available.
        if len(bucket) < self.k:

            bucket.append(contact)

            return True

        # Bucket full.
        return False

    # --------------------------------------------------------
    # FORCE ADD
    # --------------------------------------------------------

    def force_add(self, contact):

        if (
            not contact
            or contact.node_id
            == self.local_node_id
        ):
            return False

        index = get_bucket_index(
            self.local_node_id,
            contact.node_id
        )

        if index is None:
            return False

        bucket = self.buckets[index]

        # Refresh existing.
        for old in bucket:

            if old.node_id == contact.node_id:

                bucket.remove(old)
                bucket.append(contact)

                return True

        # Remove oldest if necessary.
        if len(bucket) >= self.k:

            bucket.pop(0)

        bucket.append(contact)

        return True

    # --------------------------------------------------------
    # REMOVE
    # --------------------------------------------------------

    def remove(self, node_id):

        for bucket in self.buckets:

            for contact in list(bucket):

                if contact.node_id == node_id:

                    bucket.remove(contact)

                    return True

        return False

    # --------------------------------------------------------
    # ALL CONTACTS
    # --------------------------------------------------------

    def all_contacts(self):

        result = []

        for bucket in self.buckets:
            result.extend(bucket)

        return result

    # --------------------------------------------------------
    # CLOSEST CONTACTS
    # --------------------------------------------------------

    def closest(
        self,
        target_id,
        count=K
    ):

        contacts = self.all_contacts()

        contacts.sort(
            key=lambda contact:
                xor_distance(
                    contact.node_id,
                    target_id
                )
        )

        return contacts[:count]

    # --------------------------------------------------------
    # FIND CONTACT
    # --------------------------------------------------------

    def get(self, node_id):

        for bucket in self.buckets:

            for contact in bucket:

                if contact.node_id == node_id:
                    return contact

        return None

    # --------------------------------------------------------
    # SIZE
    # --------------------------------------------------------

    def size(self):

        return sum(
            len(bucket)
            for bucket in self.buckets
        )

    # --------------------------------------------------------
    # STATISTICS
    # --------------------------------------------------------

    def statistics(self):

        return {
            "k": self.k,
            "bucket_count": ID_BITS,
            "contacts": self.size(),
            "non_empty_buckets": sum(
                1
                for bucket in self.buckets
                if bucket
            ),
        }


# ============================================================
# KADEMLIA DISCOVERY
# ============================================================

class KademliaDiscovery:

    def __init__(
        self,
        node,
        k=K,
        alpha=ALPHA
    ):

        self.node = node

        self.k = max(
            1,
            int(k)
        )

        self.alpha = max(
            1,
            int(alpha)
        )

        self.routing_table = RoutingTable(
            self.node.node_id,
            self.k
        )

        self.running = False

        self.refresh_task = None

        # ----------------------------------------------------
        # Pending FIND_NODE requests.
        #
        # request_id -> Future
        # ----------------------------------------------------

        self.pending_requests = {}

        # ----------------------------------------------------
        # Register Kademlia handlers with the EXISTING
        # MeshWeaver networking layer.
        # ----------------------------------------------------

        self.node.register_handler(
            KADEMLIA_PING,
            self._handle_ping
        )

        self.node.register_handler(
            KADEMLIA_PONG,
            self._handle_pong
        )

        self.node.register_handler(
            KADEMLIA_FIND_NODE,
            self._handle_find_node
        )

        self.node.register_handler(
            KADEMLIA_FIND_NODE_RESPONSE,
            self._handle_find_node_response
        )

    # ========================================================
    # LOCAL CONTACT
    # ========================================================

    def local_contact(self):

        return Contact(
            node_id=self.node.node_id,
            host=self.node.host,
            port=self.node.port
        )

    # ========================================================
    # START
    # ========================================================

    async def start(self):

        if self.running:
            return

        self.running = True

        self.refresh_task = asyncio.create_task(
            self._refresh_loop()
        )

        logger.info(
            "Kademlia started: %s",
            self.node.node_id
        )

    # ========================================================
    # STOP
    # ========================================================

    async def stop(self):

        self.running = False

        if self.refresh_task:

            self.refresh_task.cancel()

            try:
                await self.refresh_task

            except asyncio.CancelledError:
                pass

            self.refresh_task = None

        for future in list(
            self.pending_requests.values()
        ):

            if not future.done():
                future.cancel()

        self.pending_requests.clear()

    # ========================================================
    # ADD PEER
    # ========================================================

    def add_peer(
        self,
        node_id,
        host,
        port
    ):

        contact = Contact(
            node_id=str(node_id),
            host=str(host),
            port=int(port)
        )

        return self.routing_table.add(
            contact
        )

    # ========================================================
    # ADD CONTACT
    # ========================================================

    async def add_contact(
        self,
        contact
    ):

        if (
            contact.node_id
            == self.node.node_id
        ):
            return False

        added = self.routing_table.add(
            contact
        )

        if added:
            return True

        # ----------------------------------------------------
        # Bucket full.
        #
        # Test the oldest node.
        # ----------------------------------------------------

        index = get_bucket_index(
            self.node.node_id,
            contact.node_id
        )

        if index is None:
            return False

        bucket = self.routing_table.buckets[
            index
        ]

        if not bucket:
            return self.routing_table.force_add(
                contact
            )

        oldest = bucket[0]

        alive = await self._ping_contact(
            oldest
        )

        if alive:
            # Keep existing live contact.
            return False

        # Replace dead contact.
        self.routing_table.remove(
            oldest.node_id
        )

        return self.routing_table.force_add(
            contact
        )

    # ========================================================
    # GET PEERS
    # ========================================================

    async def get_peers(self):

        return self.routing_table.all_contacts()

    # ========================================================
    # GET PEER TUPLES
    # ========================================================

    async def get_peer_addresses(self):

        return [
            (
                contact.host,
                contact.port
            )
            for contact
            in self.routing_table.all_contacts()
        ]

    # ========================================================
    # PING
    # ========================================================

    async def _ping_contact(
        self,
        contact
    ):

        try:

            # Use the project's existing ping method
            # when available.

            if hasattr(
                self.node,
                "ping"
            ):

                result = await self.node.ping(
                    contact.host,
                    contact.port,
                    timeout=RPC_TIMEOUT
                )

                return result is not False

        except Exception:
            pass

        return False

    # ========================================================
    # INCOMING PING
    # ========================================================

    async def _handle_ping(
        self,
        message,
        addr
    ):

        contact = Contact(
            node_id=str(
                message.sender_id
            ),
            host=str(addr[0]),
            port=int(addr[1])
        )

        await self.add_contact(
            contact
        )

        response = Message(
            KADEMLIA_PONG,
            self.node.node_id,
            payload={
                "node_id":
                    self.node.node_id,

                "host":
                    self.node.host,

                "port":
                    self.node.port
            },
            msg_id=message.msg_id
        )

        self.node.send_udp(
            addr[0],
            addr[1],
            response
        )

    # ========================================================
    # INCOMING PONG
    # ========================================================

    async def _handle_pong(
        self,
        message,
        addr
    ):

        contact = Contact(
            node_id=str(
                message.sender_id
            ),
            host=str(addr[0]),
            port=int(addr[1])
        )

        await self.add_contact(
            contact
        )

        future = self.pending_requests.get(
            message.msg_id
        )

        if (
            future
            and not future.done()
        ):

            future.set_result(
                True
            )

    # ========================================================
    # FIND NODE REQUEST
    # ========================================================

    async def _handle_find_node(
        self,
        message,
        addr
    ):

        # Learn about the sender.
        sender = Contact(
            node_id=str(
                message.sender_id
            ),
            host=str(addr[0]),
            port=int(addr[1])
        )

        await self.add_contact(
            sender
        )

        payload = (
            message.payload
            or {}
        )

        target_id = payload.get(
            "target_id"
        )

        if not target_id:
            return

        closest = self.routing_table.closest(
            target_id,
            self.k
        )

        response = Message(
            KADEMLIA_FIND_NODE_RESPONSE,
            self.node.node_id,
            payload={
                "target_id":
                    target_id,

                "contacts": [
                    contact.to_dict()
                    for contact in closest
                ]
            },
            msg_id=message.msg_id
        )

        self.node.send_udp(
            addr[0],
            addr[1],
            response
        )

    # ========================================================
    # FIND NODE RESPONSE
    # ========================================================

    async def _handle_find_node_response(
        self,
        message,
        addr
    ):

        sender = Contact(
            node_id=str(
                message.sender_id
            ),
            host=str(addr[0]),
            port=int(addr[1])
        )

        await self.add_contact(
            sender
        )

        contacts = []

        payload = (
            message.payload
            or {}
        )

        for item in payload.get(
            "contacts",
            []
        ):

            try:

                contacts.append(
                    Contact.from_dict(
                        item
                    )
                )

            except (
                KeyError,
                TypeError,
                ValueError
            ):
                continue

        future = self.pending_requests.get(
            message.msg_id
        )

        if (
            future
            and not future.done()
        ):

            future.set_result(
                contacts
            )

    # ========================================================
    # FIND NODE RPC
    # ========================================================

    async def _find_node_rpc(
        self,
        contact,
        target_id
    ):

        message = Message(
            KADEMLIA_FIND_NODE,
            self.node.node_id,
            payload={
                "target_id": target_id
            }
        )

        loop = asyncio.get_running_loop()

        future = loop.create_future()

        self.pending_requests[
            message.msg_id
        ] = future

        try:

            self.node.send_udp(
                contact.host,
                contact.port,
                message
            )

            result = await asyncio.wait_for(
                future,
                timeout=RPC_TIMEOUT
            )

            return result or []

        except (
            asyncio.TimeoutError,
            OSError,
            ConnectionError
        ):

            return []

        finally:

            self.pending_requests.pop(
                message.msg_id,
                None
            )

    # ========================================================
    # ITERATIVE FIND NODE
    # ========================================================

    async def find_node(
        self,
        target_id
    ):

        shortlist = (
            self.routing_table.closest(
                target_id,
                self.k
            )
        )

        if not shortlist:
            return []

        queried = set()

        while True:

            candidates = [
                contact
                for contact
                in shortlist
                if contact.node_id
                not in queried
            ]

            if not candidates:
                break

            candidates.sort(
                key=lambda contact:
                    xor_distance(
                        contact.node_id,
                        target_id
                    )
            )

            batch = candidates[
                :self.alpha
            ]

            for contact in batch:
                queried.add(
                    contact.node_id
                )

            responses = await asyncio.gather(
                *[
                    self._find_node_rpc(
                        contact,
                        target_id
                    )
                    for contact in batch
                ],
                return_exceptions=True
            )

            changed = False

            for response in responses:

                if isinstance(
                    response,
                    Exception
                ):
                    continue

                for contact in response:

                    if (
                        contact.node_id
                        == self.node.node_id
                    ):
                        continue

                    before = (
                        self.routing_table.get(
                            contact.node_id
                        )
                    )

                    await self.add_contact(
                        contact
                    )

                    if before is None:
                        changed = True

                    if not any(
                        existing.node_id
                        == contact.node_id
                        for existing
                        in shortlist
                    ):

                        shortlist.append(
                            contact
                        )

                        changed = True

            shortlist.sort(
                key=lambda contact:
                    xor_distance(
                        contact.node_id,
                        target_id
                    )
            )

            shortlist = shortlist[
                :self.k
            ]

            if not changed:
                break

        return shortlist

    # ========================================================
    # BOOTSTRAP
    # ========================================================

    async def bootstrap(
        self,
        host,
        port,
        node_id
    ):
        """
        Join an existing MeshWeaver mesh.

        Only ONE bootstrap peer is required initially.
        """

        bootstrap_contact = Contact(
            node_id=str(node_id),
            host=str(host),
            port=int(port)
        )

        added = await self.add_contact(
            bootstrap_contact
        )

        if not added:

            # It may already be present.
            if self.routing_table.get(
                bootstrap_contact.node_id
            ) is None:

                return []

        discovered = await self.find_node(
            self.node.node_id
        )

        for contact in discovered:

            await self.add_contact(
                contact
            )

        return await self.get_peers()

    # ========================================================
    # DISCOVER
    # ========================================================

    async def discover(self):

        return await self.find_node(
            self.node.node_id
        )

    # ========================================================
    # REFRESH
    # ========================================================

    async def refresh(self):

        if self.routing_table.size() == 0:
            return []

        target = make_node_id()

        return await self.find_node(
            target
        )

    # ========================================================
    # MAINTENANCE
    # ========================================================

    async def _refresh_loop(self):

        while self.running:

            try:

                await asyncio.sleep(
                    REFRESH_INTERVAL
                )

                if self.running:
                    await self.refresh()

            except asyncio.CancelledError:
                break

            except Exception as exc:

                logger.debug(
                    "Kademlia refresh error: %s",
                    exc
                )

    # ========================================================
    # ROUTING TABLE INFO
    # ========================================================

    def statistics(self):

        result = (
            self.routing_table.statistics()
        )

        result.update({
            "node_id":
                self.node.node_id,

            "host":
                self.node.host,

            "port":
                self.node.port,

            "alpha":
                self.alpha,

            "running":
                self.running
        })

        return result

    # ========================================================
    # CLOSEST PEERS
    # ========================================================

    async def closest_peers(
        self,
        target_id,
        count=K
    ):

        return self.routing_table.closest(
            target_id,
            count
        )